runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:fswXrVcu/uOi8tYg/W8NS1ZegljZ6dL9+xC5gD31lSg=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
